kind: Service
apiVersion: v1
metadata:
  name: nginx-lb 
spec:
  type: LoadBalancer
  selector:
    project: expense
    component: backend
    environment: dev 
    version: "1.0.1"
    demo: lb
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    nodeport: 30006
---
kind: Pod
apiVersion: v1
metadata:
  name: backend-lb
  labels:
    project: expense
    component: backend
    environment: dev 
    version: "1.0.1"
    demo: lb
spec:
  containers:
  - name: nginx
    image: nginx