kind: ReplicaSet
apiVersion: apps/v1
metadata:
  name: nginx
  # These labels are replica set labels
  labels:
    app: frontend
    tier: web
spec:
  # Modify replicas according to your case
  replicas: 3
  selector:
    # Replicaset use these labels to find the pods for creating desired number of replicas
    matchLabels:
      app: frontend
      tier: web
  # Pod template
  template:
    metadata:
      labels:
        app: frontend
        tier: web
    spec:
      containers:
      - name: nginx
        image: nginx