kind: Pod
apiVersion: v1
metadata:
  name: sa-demo
  namespace:: expense
spec:
  serviceAccount: expense-mysql-secret
  initContainers:
  - name: init-myservice
    image: busybox:1.28
  containers:
  - name: nginx
    image: nginx